export const pageTitles = {
  signupPage: `PMS | Signup`,
  loginPage: `PMS | Login`,
  analyticsPage: `PMS | Dashboard`,
  accessDeniedPage: `PMS | Access Denied`,
  crmAnalyticsPage: `CRM | Dashboard`,
  crmContactPage: `CRM | Contact`,
  crmContactDetailPage: `CRM | Contact | Detail`,
  crmCreateContactPage: `CRM | Contact | Create`,
  crmFormPage: `CRM | Form`,
  settingPage: `PMS | Settings`,
  settingAccountPage: `PMS | Settings | Account`,
  settingProfilePage: `PMS | Settings | Profile`,
  settingPreferencesPage: `PMS | Settings | Preferences`,
};
